### ISSUE TITLE
Useless break-line between css properties

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [zeplin/stylesheet-extensions#14]
When copy some of properties by selecting lines and then copy text, when paste test has a break-line between lines.

![Screenshot from 2020-06-29 20-37-59](https://user-images.githubusercontent.com/17345129/86029490-7a456000-ba48-11ea-8172-1aaadafbba78.png)
![Screenshot from 2020-06-29 20-38-06](https://user-images.githubusercontent.com/17345129/86029484-787b9c80-ba48-11ea-86b1-e7c76491d297.png)

**Comment by dirtybit** [comment]
Hey @AmirHosseinKarimi 👋 

Thanks for reporting this.

The extension output is fine but it seems like these extra newlines appear when the content is copied using the web app. I can reproduce this on Firefox but it doesn't happen on Chromium-based browsers. So, this is something we need to address in the web app.

**Comment by AmirHosseinKarimi** [comment]
Hi again, I can produce this problem yet, I don't know why Firefox add break lines, But what about to remove these useless lines when copy output by selecting css?
