### ISSUE TITLE
Bug when generating line-height

### ISSUE THREAD

**Issue by jjoselv** [zeplin/stylesheet-extensions#16]
Hi!

It seems that when I generate the CSS snippets for my typography (that has 20px of line-height) it translates as simply '1.43'.

Here is a snapshot:
https://pasteboard.co/Jq8LaEU.png

Can you help me?
Thanks!

**Comment by dirtybit** [comment]
Hey @jjoselv,

CSS extension generates unitless values for line-height property when the "Unitless line-height" option is enabled. You can alter this behavior by disabling the option (attached a screen recording). 

Let us know if you need any help!

![unitless-line-height](https://user-images.githubusercontent.com/721036/92513981-02bd4b00-f1c6-11ea-953a-e464b9a7da6c.gif)

**Comment by jjoselv** [comment]
Hmm is it possible to put rems in line-height?

**Comment by dirtybit** [comment]
Yes, `line-height` values have rem unit if "Use rem unit" option is enabled.
